USE master;
GO

IF OBJECT_ID ('Student') IS NOT NULL
DROP TABLE Student;

IF OBJECT_ID('Instructor') IS NOT NULL
DROP TABLE Instructor;

IF OBJECT_ID('Department') IS NOT NULL
DROP TABLE Department;

IF OBJECT_ID('Course') IS NOT NULL
DROP TABLE Course;

GO

USE gp0541031;
 
 CREATE TABLE Students(
 StudentID INT NOT NULL PRIMARY KEY IDENTITY,
 FirstName VARCHAR(20) NOT NULL,
 LastName VARCHAR(20) NOT NULL,
 BirthDate DATE NOT NULL,
 Gender VARCHAR(6) NOT NULL, 
 PhoneNumber VARCHAR(20) NOT NULL,
 GPA INT NOT NULL,
 StateAbb VARCHAR(2) NOT NULL);
 
 CREATE TABLE Instructors(
 InstructorID INT NOT NULL PRIMARY KEY IDENTITY,
 FirstName VARCHAR(20) NOT NULL,
 LastName VARCHAR(20) NOT NULL,
 HeldDegree VARCHAR(40) NOT NULL,
 ShcoolAttended VARCHAR(50) NOT NULL);
 
 CREATE TABLE Department(
 DeptID INT NOT NULL PRIMARY KEY IDENTITY,
 ProgramCode INT NOT NUll,
 Dean VARCHAR(41) NOT NULL,
 Division VARCHAR(30) NOT NULL);
 
 CREATE TABLE Course(
 CourseID INT NOT NULL PRIMARY KEY IDENTITY,
 StudentID INT NOT NULL REFERENCES Students(StudentID),
 InstructorID INT NOT NULL REFERENCES Instructors(InstructorID),
 DeptID INT NOT NULL REFERENCES Department(DeptID),
 CreditHours INT NOT NULL,
 DaysOffered DATE NOT NULL,
 Semester VARCHAR(6) NOT NULL,
 RoomNumber VARCHAR(10) NOT NULL,
 SectionNumber VARCHAR(10) NOT NULL,
 CourseTitle VARCHAR(30) NOT NULL,
 Subject VARCHAR(30) NOT NULL);
  